apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus
    
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: log_monitoring
    user: root
    secureJsonData:
      password: password
    editable: true
    uid: mysql
